# Generated by Django 4.2.4 on 2023-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('grade', models.IntegerField()),
                ('institution', models.TextField()),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
