# Generated by Django 4.2.4 on 2023-08-16 16:30

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_course_hardskill_language_proud_referee_softskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=landing.models.PathAndRename('course/')),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=landing.models.PathAndRename('education/')),
        ),
        migrations.AlterField(
            model_name='proud',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=landing.models.PathAndRename('course/')),
        ),
    ]
